-- =====================================================================
-- Real-Time Flights Data Warehouse bootstrap
-- =====================================================================

-- STAGING (flat)
DROP TABLE IF EXISTS fact_flight_status_staging;
CREATE TABLE fact_flight_status_staging (
    flight_key           TEXT NOT NULL,
    flight_date          DATE,
    status               TEXT,
    ingest_time          TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    flight_number        TEXT,
    flight_iata          TEXT,
    flight_icao          TEXT,

    airline_iata         TEXT,
    airline_icao         TEXT,
    airline_name         TEXT,

    dep_airport          TEXT,
    dep_airport_iata     TEXT,
    dep_airport_icao     TEXT,
    dep_terminal         TEXT,
    dep_gate             TEXT,
    dep_scheduled        TIMESTAMPTZ,
    dep_estimated        TIMESTAMPTZ,
    dep_actual           TIMESTAMPTZ,
    dep_delay_min        FLOAT CHECK (dep_delay_min IS NULL OR dep_delay_min >= 0),

    arr_airport          TEXT,
    arr_airport_iata     TEXT,
    arr_airport_icao     TEXT,
    arr_terminal         TEXT,
    arr_gate             TEXT,
    arr_scheduled        TIMESTAMPTZ,
    arr_estimated        TIMESTAMPTZ,
    arr_actual           TIMESTAMPTZ,
    arr_delay_min        FLOAT CHECK (arr_delay_min IS NULL OR arr_delay_min >= 0)
);

CREATE INDEX IF NOT EXISTS idx_stg_flight_key   ON fact_flight_status_staging (flight_key);
CREATE INDEX IF NOT EXISTS idx_stg_dep_sched    ON fact_flight_status_staging (dep_scheduled);
CREATE INDEX IF NOT EXISTS idx_stg_arr_sched    ON fact_flight_status_staging (arr_scheduled);
CREATE INDEX IF NOT EXISTS idx_stg_airline_iata ON fact_flight_status_staging (airline_iata);
CREATE INDEX IF NOT EXISTS idx_stg_ingest_time  ON fact_flight_status_staging (ingest_time);

-- DIMENSIONS
DROP TABLE IF EXISTS dim_airline CASCADE;
CREATE TABLE dim_airline (
    airline_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    iata            TEXT UNIQUE,
    icao            TEXT,
    airline_name    TEXT
);

DROP TABLE IF EXISTS dim_airport CASCADE;
CREATE TABLE dim_airport (
    airport_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    iata            TEXT UNIQUE,
    icao            TEXT UNIQUE,
    airport_name    TEXT
);

DROP TABLE IF EXISTS dim_route CASCADE;
CREATE TABLE dim_route (
    route_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dep_airport_id  INTEGER NOT NULL REFERENCES dim_airport(airport_id),
    arr_airport_id  INTEGER NOT NULL REFERENCES dim_airport(airport_id),
    CONSTRAINT uq_route UNIQUE (dep_airport_id, arr_airport_id)
);

-- FACT
DROP TABLE IF EXISTS fact_flight_status;
CREATE TABLE fact_flight_status (
    flight_key       TEXT PRIMARY KEY,
    flight_date      DATE,
    status           TEXT,
    ingest_time      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    airline_id       INTEGER REFERENCES dim_airline(airline_id),
    route_id         INTEGER REFERENCES dim_route(route_id),

    dep_scheduled    TIMESTAMPTZ,
    dep_estimated    TIMESTAMPTZ,
    dep_actual       TIMESTAMPTZ,
    dep_delay_min    FLOAT CHECK (dep_delay_min IS NULL OR dep_delay_min >= 0),

    arr_scheduled    TIMESTAMPTZ,
    arr_estimated    TIMESTAMPTZ,
    arr_actual       TIMESTAMPTZ,
    arr_delay_min    FLOAT CHECK (arr_delay_min IS NULL OR arr_delay_min >= 0),

    last_updated     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_fact_dep_sched     ON fact_flight_status (dep_scheduled);
CREATE INDEX IF NOT EXISTS idx_fact_arr_sched     ON fact_flight_status (arr_scheduled);
CREATE INDEX IF NOT EXISTS idx_fact_airline_id    ON fact_flight_status (airline_id);
CREATE INDEX IF NOT EXISTS idx_fact_route_id      ON fact_flight_status (route_id);
CREATE INDEX IF NOT EXISTS idx_fact_flight_date   ON fact_flight_status (flight_date);
CREATE INDEX IF NOT EXISTS idx_fact_last_updated  ON fact_flight_status (last_updated);
